#!/bin/sh
#
# Project: Quizmaster
# Date: January 6th, 2005
# Last Modified: Januar 19th, 2005
#
# --
# This script is used to compile the project sources,
# generate the RMI-Stubs, and copy the latter to the
# network location where they are expected by the
# Quizmaster application.
#
# --
# Usage:
#
# compile <option>
# Available options:
#	all - compile all sources
#	server - only compile server sources
#	client - only compile client sources
#	messaging - only compile messaging sources
#

# Check for correct usage
if [ $# -ne 1 ]; then
echo "Usage: compile <option>"
echo "Available options:"
echo "all - compile all sources"
echo "server - compile server sources"
echo "client - compile client sources"
echo "messaging - compile messaging sources"
echo "xml - compile xml sources"
echo ""
exit -1
fi

# Compile the server sources
if [ $1 = "all" ] || [ $1 = "messaging" ]; then
echo "Compiling messaging sources..."
javac messaging/*.java
cp messaging/*.class /Library/WebServer/Documents/classes/
cp messaging/*.class ~/Sites/messaging/
fi

# Compile the xml sources
if [ $1 = "all" ] || [ $1 = "xml" ]; then
echo "Compiling xml sources..."
javac xml/*.java
fi

# Compile the server sources
if [ $1 = "all" ] || [ $1 = "server" ]; then
echo "Compiling server sources..."
javac server/*.java
echo "Generating server stub..."
rmic server.QuizServant
echo "Transfering server stub..."
cp server/QuizServant_Stub.class /Library/WebServer/Documents/classes/
fi


# Compile the applet sources
if [ $1 = "all" ] || [ $1 = "applet" ]; then
echo "Compiling applet..."
javac client/ClientApplet.java
echo "Generating applet stub..."
rmic client.ClientApplet
echo "Transfering applet stub..."
cp client/ClientApplet_Stub.class /Library/WebServer/Documents/classes/
fi

# Compile the testclient sources
if [ $1 = "client" ]; then
echo "Compiling client sources..."
javac client/*.java
echo "Generating client stub..."
rmic client.SimpleClient
echo "Transfering client stub.."
cp client/SimpleClient_Stub.class /Library/WebServer/Documents/classes/
fi

echo "Finished..."
echo ""

