#!/bin/sh
#
# Project: Quizmaster
# Date: January 6th, 2005
# Last Modified: Januar 17th, 2005
#
# --
# This script is used to start the server application
# of the Quizmaster project.
#
# --
# Usage:
# start <option>
# Available options:
#	server - Starts the server application
#	client - Starts the client application

if [ $# -gt 2 ]; then
echo "Usage: start <option>";
echo "Available options:";
echo "server - starts the server application";
echo "client - starts the cli-client";
echo "applet - starts the client applet";
echo "xml <filename>- starts xml filebuilder";
echo "";
exit -1;
fi

if [ $1 = "server" ]; then
java server.QuizServer $2
fi

if [ $1 = "client" ]; then
java client.SimpleClient $2
fi

if [ $1 = "xml" ]; then
java xml.FileBuilder $2
fi

if [ $1 = "applet" ]; then
/Library/Java/home/bin/appletviewer applet.php &
fi